### ISSUE TITLE
Can't change theme

### ISSUE THREAD

**Issue by ocdtrekkie** [jparyani/GhostSS#3]
When I try to change the theme, and save, the grain gets significantly larger, but does not change the theme on the live site. `exec error: Error: Command failed:` appears twice in the log after all of the GET commands that occur when you save the change.

**Comment by ocdtrekkie** [comment]
My grain got about 3 MB larger for each theme I tried to load.

**Comment by jparyani** [comment]
Gah somehow Ghost no longer likes the symlink hackery I did to get themes working. I've changed it around a bit and it's working now. An interesting side effect of this change is that the `themes` directory is fully under the user's control now. You could backup a grain, copy a theme to data/ghostcms/content/themes and restore the grain to upload your own themes. Not the easiest process at the moment, so we should add a web uploader or something...

Also, the reason your grain is growing is because the wget process that creates the static site is failing, and is leaving cruft around. It should be auto-cleaned up on grain startup (you may have to manually click the restart button in the sandstorm shell UI).

Can you try out https://alpha.sandstorm.io/install/90d47c64cf3701e69cf12937a758a5b5?url=http://sandstorm.io/apps/jparyani/ghost-9.spk to make sure it works fine for you? One other slight regression is that changing themes doesn't immediately update the static site. For now, you'll have to change your theme, and then update a post.

Also another issue is that some themes require static pages to be created for them to work. Specifically peeves and readium require some. Check the log to see which endpoints are returning 404 when a publish happens and add a static page for each (see http://www.ghostforbeginners.com/how-to-publish-a-page-on-your-ghost-blog/).

**Comment by ocdtrekkie** [comment]
Working well for me, and the grain size is indeed back to normal. Awesome that it's now possible to use your own themes.

**Comment by ocdtrekkie** [comment]
Fixed via 72bfad468eb201b8b60856fd59e24a3d580034e8
